# Generated by Django 4.2.13 on 2024-06-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
